---
title: "Power BI model details"
author: "Marius Sandu"
date: "11/23/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RDCOMClient)
library(dplyr)
library(magrittr)
library(data.table)
library(jsonlite)

dmv_queries <- fromJSON("dmv.json")

# unlist bad, NULLs can't be inside R vectors
# so it breaks the structure, when using unlist.

get_value <- function(x) {
  get_v1 <- function (x) {
    result <- x[[1]] # kinda retarded, but works
    return(result) 
  }
  result <- sapply(x, get_v1)
  return(result)
}

rowset_to_DT <- function(x, headers) {
  result <- x %>%
    sapply(get_value) %>%
    as.data.table() %>%
    t() %>%
    as.data.table() %>%
    mutate(across(where(is.list), as.character))
  
  colnames(result) <- headers
  setkey(result, 'ID')
  return(result)
}

build_query <- function(view, headers) {
  result <- paste(
    'select',
    paste0('[', headers, ']', collapse = ","),
    paste0('from $system.', view)
  )
  return(result)
}

```


```{r}
# TODO: the port can be scanned from the localappdata folder, and the initial catalogue retrieved via a DMV query
con <- COMCreate("ADODB.Connection")
con[["ConnectionString"]] <- paste(
  "Provider=MSOLAP.8",
  "Integrated Security=SSPI",
  "Persist Security Info=True",
  "Data Source=localhost:63231",
  "Initial Catalog=314f0f2c-814f-43c8-bc7b-7c867e7ca52c",
  sep = ";")

con$Open()
``` 

## Getting raw tables

```{r echo=FALSE}
# TODO: This still looks kinda wonky

relationships_headers <- dmv_queries[dmv_queries$view == 'TMSCHEMA_RELATIONSHIPS',]$headers[[1]]

relationships <- con$Execute(
    build_query('TMSCHEMA_RELATIONSHIPS', relationships_headers)
  )$GetRows() %>%
    rowset_to_DT(headers = relationships_headers)

tables_headers <- dmv_queries[dmv_queries$view == 'TMSCHEMA_TABLES',]$headers[[1]]

tables <- con$Execute(
    build_query('TMSCHEMA_TABLES', tables_headers)
  )$GetRows() %>%
    rowset_to_DT(headers = tables_headers)

columns_headers <- dmv_queries[dmv_queries$view == 'TMSCHEMA_COLUMNS',]$headers[[1]]

columns <- con$Execute(
    build_query('TMSCHEMA_COLUMNS', columns_headers)
  )$GetRows() %>%
    rowset_to_DT(headers = columns_headers) 

measures_headers <- dmv_queries[dmv_queries$view == 'TMSCHEMA_MEASURES',]$headers[[1]]

measures <- con$Execute(
    build_query('TMSCHEMA_MEASURES', measures_headers)
  )$GetRows() %>%
    rowset_to_DT(headers = measures_headers)

```

### Tables

```{r}
tables %>%
  mutate(
    'Is auto generated date table' = grepl('LocalDateTable_[A-Za-z0-9_\\-]{36}', Name )
  ) %>%
  select(
    'Table' = Name,
    'Data Category' = DataCategory,
    'Hidden' = IsHidden,
    'Excluded from refresh' = ExcludeFromModelRefresh,
    'Is auto generated date table'
  )
```
### Columns in model

```{r}
columns %>%
  left_join(tables, by = c("TableID" = "ID"))  %>%
  left_join(columns, by = c("ID" = "SortByColumnID")) %>%
  select(
    'Table' = 'Name',
    'Column' = 'ExplicitName.x',
    'Data category' = 'DataCategory.x',
    'Is hidden' = 'IsHidden.x',
    'Is unique' = 'IsUnique.x',
    'Sorted by' = 'ExplicitName.y'
  )
```

